### ISSUE TITLE
error when running nav2 stack

### ISSUE THREAD

**Issue by lenhatquang2512** [arshadlab/turtlebot3_multi_robot#1]
Hey, thank you for this good repo.

m a ROS2 beginner, and I am trying to implement navigation with multiple turtlebots similarly as you did. To generate multiple robots, I tested your code, and it ran successfully with ROS2 foxy, but I have some errors when trying to run Nav2 stack. 

![Screenshot from 2023-06-21 11-56-11](https://github.com/arshadlab/turtlebot3_multi_robot/assets/72292146/ad03a0b6-d146-46b7-9921-0fba151eb4ec)

The error was in the figure. Could you tell me how to solve this? Thank you a lot.

**Comment by arshadlab** [comment]
Hi,
  Plz use foxy branch.  master is for ROS2 humble. 
Guide:  https://medium.com/@arshad.mehmood/a-guide-to-multi-robot-navigation-utilizing-turtlebot3-and-nav2-cd24f96d19c6.

**Comment by lenhatquang2512** [comment]
Thank you ! It was really helpful. I confirmed it worked perfectly in my machine.  I have a small question, for each independent Turtlebot3, we can each set each one initial 2D Pose and then use 2D Nav Goal right ? And all the robots will avoid each other as well during navigation ? Sorry I am new to Navigation concept so maybe I will misunderstand something.

**Comment by arshadlab** [comment]
Your understanding is correct on 2D pose and 2D Nav Goal. except that the robot's may not be able to avoid each other completely due to the lidar sensor.  The sensor is located on the top and it will scan horizontal area only at that level which will not completely detect other robot body and only the other robot's sensor part area resulting in a possible collision.  A visual SLAM would be suitable for a better solution.
